steps:
  - name: build-react-app
    image: node:24-alpine
    commands:
      - npm install -g bun
      - bun install --legacy-peer-deps
      - bun run build

  - name: prepare-server
    image: appleboy/drone-ssh
    settings:
      host:
        from_secret: ssh_host
      username:
        from_secret: ssh_user
      password:
        from_secret: ssh_pass
      script:
        - rm -rf /home/zein/projects/taki-react
        - mkdir -p /home/zein/projects/taki-react

  - name: deploy-to-server
    image: appleboy/drone-scp
    settings:
      host:
        from_secret: ssh_host
      username:
        from_secret: ssh_user
      password:
        from_secret: ssh_pass
      target: /home/zein/projects/taki-react
      source: dist/*
      strip_components: 1
      overwrite: true

  - name: restart-pm2
    image: appleboy/drone-ssh
    settings:
      host:
        from_secret: ssh_host
      username:
        from_secret: ssh_user
      password:
        from_secret: ssh_pass
      script:
        - export PATH=/home/zein/.nvm/versions/node/v24.13.0/bin:/home/zein/.bun/bin:$PATH
        - cd /home/zein/projects/taki-react
        - pm2 delete taki-react || true
        - pm2 start "bun x serve . -p 3010" --name "taki-react"