clone:
  image: woodpeckerci/plugin-git

steps:
  name: build react app
  image: node:20-alpine
  commands:
    - npm install
    - npm run build

  name: deploy to server
  image: alpine:3.19
  commands:
    - rm -rf /home/zein/projects/taki-react/*
    - cp -r /woodpecker/src/github.com/username/react-repo/build/* /home/zein/projects/taki-react/
    - pm2 delete taki-react 2>/dev/null || true
    - pm2 start "bun run --bun index.html -p 3010" --name "taki-react"