steps:
  - name: build-react-app
    # Gunakan image resmi Bun (oven/bun)
    image: oven/bun:1-alpine
    commands:
      - bun install
      - bun run build

  - name: deploy-to-server
    image: alpine:3.19
    commands:
      - rm -rf /home/zein/projects/taki-react/*
      # Sesuai pesan error sebelumnya, pastikan folder outputnya benar (dist atau build)
      - cp -r dist/* /home/zein/projects/taki-react/
      # Menjalankan PM2 dengan runtime Bun
      - pm2 restart taki-react || pm2 start "bun run --bun index.html -p 3010" --name "taki-react"