steps:
  - name: build-react-app
    image: node:24-alpine
    commands:
      - npm install -g bun
      - bun install --legacy-peer-deps
      - bun run build

  - name: prepare-server
    image: appleboy/drone-ssh
    settings:
      host:
        from_secret: ssh_host
      username:
        from_secret: ssh_user
      password:
        from_secret: ssh_pass
      script:
        - rm -rf /home/zein/projects/taki-react
        - mkdir -p /home/zein/projects/taki-react

  - name: deploy-to-server
    image: appleboy/drone-scp
    settings:
      host:
        from_secret: ssh_host
      username:
        from_secret: ssh_user
      password:
        from_secret: ssh_pass
      target: /home/zein/projects/taki-react
      source: dist/*
      strip_components: 1
      overwrite: true

  - name: restart-pm2
    image: appleboy/drone-ssh
    settings:
      host:
        from_secret: ssh_host
      username:
        from_secret: ssh_user
      password:
        from_secret: ssh_pass
      script:
        - cd /home/zein/projects/taki-react
        - pm2 restart taki-react || pm2 start "bun run --bun index.html -p 3010" --name "taki-react"