steps:
  - name: build-react-app
    # Pakai Node.js karena lebih stabil di CPU tanpa AVX
    image: node:20-alpine
    commands:
      # Kita pakai npm tapi skip audit & check biar cepet
      - npm install --legacy-peer-deps --no-audit
      # Langsung tembak vite build buat skip tsc (biar gak error unused variables)
      - npx vite build 

  - name: deploy-to-server
    image: alpine:3.19
    commands:
      - rm -rf /home/zein/projects/taki-react/*
      # Pastikan pakai dist/* kalau pake Vite
      - cp -r dist/* /home/zein/projects/taki-react/
      # Jalankan PM2 (dengan asumsi PM2 & Bun sudah ada di host server)
      - pm2 restart taki-react || pm2 start "bun run --bun index.html -p 3010" --name "taki-react"