steps:
  - name: build-react-app
    # Menggunakan Node versi terbaru (Current) yang stabil tanpa AVX
    image: node:24-alpine
    commands:
      - bun install
      - bun run build 

  - name: deploy-to-server
    image: appleboy/drone-scp
    settings:
      host:
        from_secret: ssh_host
      username:
        from_secret: ssh_user
      password:
        from_secret: ssh_pass
      target: /home/zein/projects/taki-react
      source: dist/*
      strip_components: 1
      overwrite: true

  - name: restart-pm2
    image: appleboy/drone-ssh
    settings:
      host:
        from_secret: ssh_host
      username:
        from_secret: ssh_user
      password:
        from_secret: ssh_pass
      script:
        # Pindah ke direktori project di host server
        - cd /home/zein/projects/taki-react
        # Restart atau start aplikasi menggunakan runtime Bun yang ada di host
        - pm2 restart taki-react || pm2 start "bun run --bun index.html -p 3010" --name "taki-react"